### ISSUE TITLE
Viewer c

### ISSUE THREAD

**Issue by b16joski** [blobtoolkit/viewer#6] opened 2020-09-07 07:13 UTC
```
#inside the viewer directory
npm install
```

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/nodemon/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/joseph/.npm/_logs/2020-09-07T06_53_28_278Z-debug.log
 Hosting the parent directory instead.
Starting BlobToolKit API on port 8001 (pid: 476312)
Starting BlobToolKit viewer on port 8081 (pid: 476333)

After I run:
```
~/blobtoolkit/blobtools2/blobtools host --port 8081 \
                                        --api-port 8001 \
                                        --hostname localhost \
                                        --viewer ~/blobtoolkit/viewer \
                                        ~/blobtoolkit/blobtoolkit_tutorial/BLOBDIR



```

> blobtoolkit-viewer@1.1.0 api /home/joseph/blobtoolkit/viewer
> node src/server/app.js

Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp.node'

- Remove the "node_modules/sharp" directory, run "npm install" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! blobtoolkit-viewer@1.1.0 api: `node src/server/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the blobtoolkit-viewer@1.1.0 api script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/joseph/.npm/_logs/2020-09-07T07_08_15_235Z-debug.log

> blobtoolkit-viewer@1.1.0 client /home/joseph/blobtoolkit/viewer
> webpack-dev-server --mode development --content-base src/client

sh: 1: webpack-dev-server: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! blobtoolkit-viewer@1.1.0 client: `webpack-dev-server --mode development --content-base src/client`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the blobtoolkit-viewer@1.1.0 client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/joseph/.npm/_logs/2020-09-07T07_08_16_731Z-debug.log

**Comment by rjchallis** [comment] 2020-09-08 07:36
Hi

I think this being caused by an issue that I fixed in the release/v1.2 branch, but I haven't merged the changes into the main branch. Could you try 

```
git checkout -b release/v1.2
npm install
```

to see if the newer code works for you?

**Comment by b16joski** [comment] 2020-09-08 20:52
Dear Challis,

Thank you for your reply.

Now I have the viewer running but giving me a different directory path
Initializing viewer |███████████████████████████████████████| 15/15 seconds
        │
Open dataset at http://localhost:8004/view/dataset/BLOBDIR/blob?
         │
For remote access use:
         │
    ssh -L 8004:127.0.0.1:8004 -L 8003:127.0.0.1:8003 username@remote_host
         │

This is the directory with the .jason files that I created
/home/joseph/blobtoolkit/blobtoolkit_tutorial/BLOBDIR

I expect the path to be like:
http://localhost:8004/view/home/joseph/blobtoolkit/blobtoolkit_tutorial/BLOBDIR

Thank you.

kind regards

*Joseph Kirangwa*
PhD student
Email: jkirangw@uni-koeln.de
*University of Cologne*

*Worm-Laboratory*
worm-lab.eu
Zülpicher Str. 47b
50674 Köln, Germany

**Comment by b16joski** [comment] 2020-09-08 23:12
Dear Challis,

npm start:
BlobToolKit RESTful API started on http port: 8000

npm run client:
compiled successfully

However, when I go to the following link in the browser, the site can't be
reached.
http://localhost:8080/view/all

Thank you


*Joseph Kirangwa*
PhD student
Email: jkirangw@uni-koeln.de
*University of Cologne*

*Worm-Laboratory*
worm-lab.eu
Zülpicher Str. 47b
50674 Köln, Germany

**Comment by b16joski** [comment] 2020-09-09 12:11
Hi,
I can't really find the viewer outputs

This is what I have from the terminal:
WARNING: Directory '/home/joseph/blobtoolkit/blobtools_test/BlobDir'
appears to be a BlobDir.
         Hosting the parent directory instead.
Starting BlobToolKit API on port 8000 (pid: 505857)
Starting BlobToolKit viewer on port 8080 (pid: 505911)
Visit http://localhost:8080 to use the interactive BlobToolKit Viewer.

Thank you

**Comment by rjchallis** [comment] 2020-09-09 14:40
Hi 

The directory path shouldn't be part of the URL once the dataset is hosted so if you have a BlobDir named `BlobDir` in a directory at `/home/joseph/blobtoolkit/blobtoolkit_tutorial`, the URL should look like `http://localhost:8080/view/dataset/BlobDir/blob`.

It seems that you've tried several different ways to host the dataset, if you run the `npm` commands directly, you'll need to set the `BTK_FILE_PATH` environment variable to the directory that contains your BlobDir before starting the API, e.g.

```
BTK_FILE_PATH=/home/joseph/blobtoolkit/blobtoolkit_tutorial npm start
```
then the viewer instance you start with `npm run client` should be able to access the datasets.

If you're still having trouble finding the datasets, it would be worth checking that the API is running correctly with a command like:

```
curl "http://localhost:8000/api/v1/search/all"
```

**Comment by b16joski** [comment] 2020-09-09 18:31
Hi,

I made changes to the BTK_FILE_PATH as recommended but still have trouble
accessing the site.
see:

(btk_env) joseph@wormlab-NUC10i5FNK-01:~/blobtoolkit/viewer$
BTK_FILE_PATH=/home/joseph/blobtoolkit/blobtoolkit_tutorial npm start

> blobtoolkit-viewer@1.1.0 start /home/joseph/blobtoolkit/viewer
> nodemon src/server/app.js

[nodemon] 2.0.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node src/server/app.js`
BlobToolKit RESTful API server started on http port: 8000

checking in the browser:
*http://localhost:8000/view/dataset/BlobDir/blob
<http://localhost:8000/view/dataset/BlobDir/blob>*

Site can't be reached.



npm run client

output:
compiled successfully.


























*Joseph Kirangwa*
PhD student
Email: jkirangw@uni-koeln.de
*University of Cologne*

*Worm-Laboratory*
worm-lab.eu
Zülpicher Str. 47b
50674 Köln, Germany


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by rjchallis** [comment] 2020-09-10 13:45
Port 8000 will be the API, so that has a different set of paths to the viewer. If you visit 

http://localhost:8000/api/v1/search/all

in a browser, you should see a JSON data structure with information about the datasets which is designed to be read by the viewer. Assuming that works, then the viewer should be able to load your datasets on port 8080:

http://localhost:8080/view/dataset/BlobDir/blob

**Comment by b16joski** [comment] 2020-09-11 12:07
Hi Richard,

I generated a blob plot but I can't see the taxa content. See attached.
It shows undef. I wonder why.

Thank you

Kind regards.

Joseph






<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by rjchallis** [comment] 2020-09-15 14:07
I'm afraid I can't see an attachment. If everything is labelled undef, it may be a problem with the input BLAST files. Could you take a look at the first few lines of your BLAST output and make sure there is a taxid in column 2?

**Comment by b16joski** [comment] 2020-09-15 14:46
Hi Richard,

Here is the attachment sorry. I am repeating the blast searches with
diamond blastx to generate new hits file.
Then I will taxify the output from the diamond. see attached.

Kind regards,

*Joseph Kirangwa*

**Comment by rjchallis** [comment] 2020-09-15 15:47
For some reason attachments don't seem to be showing up on here but taxify is not a blobtools2 command, so I suspect that the column order is not as expected.  You can specify the column order using the `--hits-cols` option to `blobtools add`:

```
  --hits-cols LIST      Comma separated list of <column number>=<field name>.
                        [Default: 1=qseqid,2=staxids,3=bitscore,5=sseqid,10=sstart,11=send,14=evalue]
```

Alternatively, provided you have the taxonomic information min your Diamond database, you can use a command like the one on [this page](https://blobtoolkit.genomehubs.org/blobtools2/blobtools2-tutorials/adding-data-to-a-dataset/adding-hits/) to include the taxonomy in the output file and make sure the column order matches the expected order.

**Closed** 2023-07-02 03:09 UTC
Labels: dormant
